name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Android SDK and build tools
        uses: r0adkll/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Ensure Gradle wrapper or install gradle
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew --version
          else
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle --version
          fi

      - name: Build APK (debug)
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug --no-daemon
          else
            gradle assembleDebug
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
